package Term::Caca::Event::Key;
# ABSTRACT: event generated by a keyboard activity

=head1 SYNOPSIS

    use Term::Caca qw/ :events /;

    my $t = Term::Caca->new;
    while ( 1 ) {
        my $event = $t->wait_for_event( 
            mask => $ANY_KEY,
        );  
        
        print "character: ", $event->char;
    }

=head1 DESCRIPTION

Generated when a key is pressed or released.

=cut

use strict;
use warnings;

use parent 'Term::Caca::Event';
use Method::Signatures;

sub new { 
    my $class = shift;
    my $self = Term::Caca::Event->new( @_ );
    return bless $self, $class;
}

=method char()

Returns the character pressed or released.

=cut

method char {
    return Term::Caca::_get_event_key_ch( $self->_event );
}

1;
