package Term::Caca::Event::Key;
# ABSTRACT: event generated by a keyboard activity

=head1 SYNOPSIS

    use Term::Caca qw/ :events /;

    my $t = Term::Caca->new;
    while ( 1 ) {
        my $event = $t->wait_for_event( 
            mask => $ANY_KEY,
        );  
        
        print "character: ", $event->char;
    }

=head1 DESCRIPTION

Generated when a key is pressed or released.

=cut

use Moo;
extends 'Term::Caca::Event';

=method char()

Returns the character pressed or released.

=cut

sub char {
    return chr Term::Caca::caca_get_event_key_ch( $_[0]->event );
}

1;
