package Term::Caca::Event::Key;
# ABSTRACT: event generated by a keyboard activity

=head1 SYNOPSIS

    use Term::Caca qw/ :events /;

    my $t = Term::Caca->new;
    while ( 1 ) {
        my $event = $t->wait_for_event( 
            mask => $ANY_KEY,
        );  
        
        print "character: ", $event->char;
    }

=head1 DESCRIPTION

Generated when a key is pressed or released.

=cut

use Moo;
extends 'Term::Caca::Event';

=method char()

Returns the character pressed or released.

=method key()

Returns the key code that was pressed or released.

These will match the values of the constants exported by the C<:keys> tag
from L<Term::Caca::Constants>.

=cut

sub key {
    return Term::Caca::caca_get_event_key_ch( $_[0]->event );
}

sub char { chr shift->key }

1;
